### ISSUE TITLE
Looking for financial tweets dataset

### ISSUE THREAD

**Issue by Dbroug01** [joemzhao/tweets-retriever#1]
Hi there,

I read your 2014 article "Stream-based active learning for sentiment analysis in the financial domain" with great interest. I am an Msc student in Data Science, looking at a similar idea of using sentiment analysis of tweets to understand how expert users' opinions can predict stock market movements for my end-of-year project. 

In your article you mention: "As a side effect, since there is no large labeled dataset of financial tweets publicly available, we have labeled and made publicly available a collection of financial tweets, making it the first large (in the sense of labeling effort) publicly available dataset of its kind".

Apologies for reaching out in this way but I cannot find the referenced dataset, this repository seems to be more generic tweets than financial tweets, presumably relating to other research? I was wondering if it would be possible to share the labeled data, as this would be invaluable for my project.

All the best,

Darcey

**Comment by joemzhao** [comment]
> I read your 2014 article "Stream-based active learning for sentiment analysis in the financial domain" ...

> In your article you mention: "As a side effect, since ...

i am not the author of the paper you mentioned so unfortunately i am not able to help you.
